const {chromium}=require('../../.perf-tools/node_modules/playwright-core');
const fs=require('node:fs/promises');
const assert=require('node:assert/strict');
(async()=>{
 const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,ignoreDefaultArgs:['--disable-back-forward-cache']});
 const p=await b.newPage({viewport:{width:1440,height:900}});
 const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{window.restored=false;addEventListener('pageshow',e=>window.restored=e.persisted);});
 await p.goto('http://127.0.0.1:8080/Home/Labs?lang=ar');
 await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer==='worker');
 await p.waitForTimeout(850);
 await p.screenshot({path:'.perf-tools/worker-ar-light.png'});
 assert.equal(await p.locator('html').getAttribute('dir'),'rtl');
 await p.evaluate(()=>window.toggleTheme());
 await p.waitForTimeout(400);
 await p.screenshot({path:'.perf-tools/worker-ar-dark.png'});
 await p.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));
 await p.waitForTimeout(150);
 assert.equal(await p.locator('#neurix-network').evaluate(e=>Number(e.style.opacity)),.28);
 await p.screenshot({path:'.perf-tools/network.png'});
 await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
 await p.locator('header a[href="/Home/About"]:visible').first().click();
 await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer==='worker');
 await p.goBack();
 await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer==='worker');
 console.log('BFCache',await p.evaluate(()=>window.restored));
 await p.setViewportSize({width:390,height:844});
 await p.reload();await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer==='worker');
 await p.waitForTimeout(850);
 await p.screenshot({path:'.perf-tools/worker-mobile.png'});
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.locator('#mobile-menu-btn').click();
 await p.locator('#mobile-menu a[href="/Home/About"]').first().click();
 await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer==='worker');
 assert.equal(new URL(p.url()).pathname,'/Home/About');
 await p.emulateMedia({reducedMotion:'reduce'});
 await p.reload();await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer==='worker');
 console.log('reduced motion',await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches));
 const fallback=await b.newPage();
 await fallback.addInitScript(()=>window.Worker=undefined);
 await fallback.goto('http://127.0.0.1:8080/Home/Labs');
 await fallback.waitForFunction(()=>document.querySelector('canvas')?.dataset.renderer==='main');
 console.log('fallback',await fallback.locator('canvas').getAttribute('data-renderer'));
 assert.deepEqual(errors,[]);console.log('PASS Arabic, themes, network, history, mobile, reduced motion, fallback');
 await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
